---
title: "R Notebook"
output: html_notebook
---


```{r }
source(file = here::here("libraries.R"), local = TRUE)$value
```
```{r}
source(file = "../01_data_clean_script/citi_bikes_clean_script.R")$value
```


## Business Introduction

### Business Processes and Data Flow

### Data Visualisation as a tool for decision-making

### Data Types

### Data Quality and Data bias

## Data Cleaning




## Data Visualisations & Insights

### Hires Per Month
```{r}

  source(file ="bikes_hired_per_month.R", local = TRUE, encoding = getOption("encoding"))$value


```



```{r}
result <- tryCatch(
    {
        source(file = here::here("03_visualisations/bikes_hired_per_month.R"), local = TRUE)
    },
    error = function(e) {
        message("Error sourcing script: ", conditionMessage(e))
        NULL
    }
)

# Check if the sourcing was successful
if (!is.null(result)) {
    # Print the result to see what it contains
    print(result)
} else {
    message("Script sourcing failed or returned NULL.")
}
```


### Hires Per Month By Gender
```{r}

```


### Hires Per Each Week Day By Customer Type
```{r}

```



### Travels Frequency
```{r}

```


### Start Stations Location
```{r}

```

